// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsNKX1NJ2t-s9OTNZdxsroSjdFWHHuhfU',
    appId: '1:878796084156:web:040fa82d612291a4f111b9',
    messagingSenderId: '878796084156',
    projectId: 'ats-database-cd6c8',
    authDomain: 'ats-database-cd6c8.firebaseapp.com',
    storageBucket: 'ats-database-cd6c8.appspot.com',
    measurementId: 'G-YZQR3ZSRGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQyugXwWsS4CuHMqEE5Byl5QuQYtn4W40',
    appId: '1:878796084156:android:d427b4048fb10509f111b9',
    messagingSenderId: '878796084156',
    projectId: 'ats-database-cd6c8',
    storageBucket: 'ats-database-cd6c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaqrMq0Ab56uwDbKjv8pol_Xmmzi-gWDM',
    appId: '1:878796084156:ios:234c414ba4716dabf111b9',
    messagingSenderId: '878796084156',
    projectId: 'ats-database-cd6c8',
    storageBucket: 'ats-database-cd6c8.appspot.com',
    iosBundleId: 'com.example.ats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaqrMq0Ab56uwDbKjv8pol_Xmmzi-gWDM',
    appId: '1:878796084156:ios:2dd54308d576d2ddf111b9',
    messagingSenderId: '878796084156',
    projectId: 'ats-database-cd6c8',
    storageBucket: 'ats-database-cd6c8.appspot.com',
    iosBundleId: 'com.example.ats.RunnerTests',
  );
}
